CREATE TYPE "Role" AS ENUM ('admin', 'instructor', 'student', 'proctor');
CREATE TYPE "ExamStatus" AS ENUM ('draft', 'scheduled', 'live', 'paused', 'completed', 'archived');

CREATE TABLE "Organization" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "slug" TEXT NOT NULL UNIQUE, "plan" TEXT NOT NULL);
CREATE TABLE "User" ("id" TEXT PRIMARY KEY, "orgId" TEXT NOT NULL REFERENCES "Organization"("id"), "email" TEXT NOT NULL UNIQUE, "name" TEXT NOT NULL, "role" "Role" NOT NULL, "password" TEXT NOT NULL);
CREATE TABLE "Question" ("id" TEXT PRIMARY KEY, "orgId" TEXT NOT NULL REFERENCES "Organization"("id"), "type" TEXT NOT NULL, "title" TEXT NOT NULL, "prompt" TEXT NOT NULL, "answerKey" TEXT[] NOT NULL, "explanation" TEXT, "tags" TEXT[] NOT NULL, "difficulty" TEXT NOT NULL, "points" INTEGER NOT NULL, "timeLimitSec" INTEGER, "mediaUrl" TEXT, "createdById" TEXT NOT NULL REFERENCES "User"("id"), "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "QuestionOption" ("id" TEXT PRIMARY KEY, "questionId" TEXT NOT NULL REFERENCES "Question"("id") ON DELETE CASCADE, "label" TEXT NOT NULL, "text" TEXT NOT NULL, "isCorrect" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "Exam" ("id" TEXT PRIMARY KEY, "orgId" TEXT NOT NULL REFERENCES "Organization"("id"), "title" TEXT NOT NULL, "description" TEXT NOT NULL, "status" "ExamStatus" NOT NULL, "joinCode" TEXT NOT NULL UNIQUE, "startsAt" TIMESTAMP, "endsAt" TIMESTAMP, "createdById" TEXT NOT NULL REFERENCES "User"("id"), "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ExamSettings" ("examId" TEXT PRIMARY KEY REFERENCES "Exam"("id") ON DELETE CASCADE, "shuffleQuestions" BOOLEAN NOT NULL, "shuffleOptions" BOOLEAN NOT NULL, "showCorrectAfterSubmit" BOOLEAN NOT NULL, "allowReview" BOOLEAN NOT NULL, "preventCopyPaste" BOOLEAN NOT NULL, "tabSwitchLimit" INTEGER NOT NULL, "cameraRequired" BOOLEAN NOT NULL, "maxAttempts" INTEGER NOT NULL, "durationMin" INTEGER NOT NULL);
CREATE TABLE "ExamQuestion" ("examId" TEXT NOT NULL REFERENCES "Exam"("id") ON DELETE CASCADE, "questionId" TEXT NOT NULL REFERENCES "Question"("id"), "order" INTEGER NOT NULL, "pointsOverride" INTEGER, PRIMARY KEY ("examId", "questionId"));
CREATE TABLE "Attempt" ("id" TEXT PRIMARY KEY, "examId" TEXT NOT NULL REFERENCES "Exam"("id"), "participantId" TEXT NOT NULL, "status" TEXT NOT NULL, "score" INTEGER NOT NULL, "maxScore" INTEGER NOT NULL, "startedAt" TIMESTAMP NOT NULL, "submittedAt" TIMESTAMP);
CREATE TABLE "AttemptAnswer" ("id" TEXT PRIMARY KEY, "attemptId" TEXT NOT NULL REFERENCES "Attempt"("id") ON DELETE CASCADE, "questionId" TEXT NOT NULL REFERENCES "Question"("id"), "selectedOptionIds" TEXT[] NOT NULL, "textAnswer" TEXT, "answeredAt" TIMESTAMP NOT NULL, "timeSpentSec" INTEGER NOT NULL, "isCorrect" BOOLEAN, "scoreAwarded" INTEGER);
CREATE TABLE "LiveRoom" ("id" TEXT PRIMARY KEY, "examId" TEXT NOT NULL REFERENCES "Exam"("id"), "joinCode" TEXT NOT NULL, "status" TEXT NOT NULL, "currentQuestionIndex" INTEGER NOT NULL, "startedAt" TIMESTAMP);
CREATE TABLE "LiveParticipant" ("id" TEXT PRIMARY KEY, "roomId" TEXT NOT NULL REFERENCES "LiveRoom"("id") ON DELETE CASCADE, "userId" TEXT, "displayName" TEXT NOT NULL, "avatarColor" TEXT NOT NULL, "joinedAt" TIMESTAMP NOT NULL, "score" INTEGER NOT NULL, "progress" INTEGER NOT NULL, "isOnline" BOOLEAN NOT NULL, "violations" INTEGER NOT NULL);
CREATE TABLE "ProctorEvent" ("id" TEXT PRIMARY KEY, "examId" TEXT NOT NULL REFERENCES "Exam"("id"), "participantId" TEXT NOT NULL, "type" TEXT NOT NULL, "severity" TEXT NOT NULL, "message" TEXT NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP NOT NULL);
